#!/bin/bash

ln -nfs ./dotfiles/.vimrc ~/.vimrc
ln -nfs ./dotfiles/.vim ~/.vim
ln -nfs ./dotfiles/.bash_profile ~/.bash_profile
ln -nfs ./dotfiles/.gitignore ~/.gitignore
ln -nfs ./dotfiles/.zshrc ~/.zshrc
